### ISSUE TITLE
positionWindow(w)

### ISSUE THREAD

**Issue by dsisnero** [ruby/tk#14]
In some of your samples  positionWindow is called for TopLevel

demos-en/entry3.rb

in tk (0.2.0)  this method is not available on my install

[6] pry(#<Tk::Toplevel>)> self.methods.map{|m| m.to_s}.select{|m| m =~ /^p/}
=> ["positionfrom",
 "protocol",
 "protocols",
 "pack_in",
 "pack_config",
 "pack_configure",
 "pack_info",
 "pack_propagate",
 "pack_slaves",
 "pack",
 "place_in",
 "pack_forget",
 "place",
 "place_forget",
 "place_configure",
 "place_configinfo",
 "place_config",
 "place_slaves",
 "place_info",
 "path",
 "pry",
 "pretty_print",
 "pretty_print_cycle",
 "pretty_print_instance_variables",
 "pretty_print_inspect",
 "public_send",
 "public_method",
 "pretty_inspect",
 "protected_methods",
 "private_methods",
 "public_methods"]

**Comment by jeremyevans** [comment]
You can't execute this script independently, it needs to be executed via `sample/demos-en/widget` (see `sample/demos-en/README.1st`).  The `positionWindow`method is defined in `sample/demos-en/widget`.

I've checked that `sample/demos-en/entry3.rb` does run correctly via `widget`, and the other files in `sample/demos-en` also use `positionWindow`.
