### ISSUE TITLE
Unknown command tk

### ISSUE THREAD

**Issue by ChangyuYan** [ruby/tk#17]
When I execute `$ gem 'tk' `

It is giving me this error: 
```
ERROR:  While executing gem ... (Gem::CommandLineError)
          Unknown command tk
```  

Help, please?

**Comment by amatsuda** [comment]
You're missing `install`. Should be
`$ gem install tk`.

**Comment by ChangyuYan** [comment]
I'm very sorry. I misread the first line from README. My apologies.
