### ISSUE TITLE
How i can install Tk !? 

### ISSUE THREAD

**Issue by abdallah-elsharif** [ruby/tk#23]
how i can install tk on ubuntu
i execute this command "gem install tk" but it failed

**Comment by jeremyevans** [comment]
`gem install tk` only installs the `tk` gem for ruby, it does not install Tcl or Tk.  You need to have Tcl and Tk installed before running `gem install tk`  A search for "ubuntu install tk" yields https://askubuntu.com/questions/239153/how-do-i-install-tk-8-5

If you have further questions about how to install Tcl or Tk on Ubuntu, please ask on an Ubuntu specific forum.  If you have problems with `gem install tk` after installing Tcl and Tk on Ubuntu, please respond with more information on your environment.
