### ISSUE TITLE
tk decreases load speed of others gems loading after it

### ISSUE THREAD

**Issue by hupeng2006** [ruby/tk#26]
If tk is loaded firstly, gems after it would take a long time to load. This becomes extreme with gem rubyXL. Here is the result:

############## first require tk, then rubyXL
t0 = Time.now
require 'tk'
puts Time.now - t0 # 1.35 secs
t0 = Time.now
require 'rubyXL'
puts Time.now - t0 # 58.6 secs

############## first require rubyXL, then tk
t0 = Time.now
require 'rubyXL'
puts Time.now - t0 # 0.28 secs
t0 = Time.now
require 'tk'
puts Time.now - t0 # 2.8 secs

my app use tk as gui. When I use ruby 2.3.1, I do not see this issue. After I upgrade to ruby 2.7.2, the issue shows up. And now I downgrade to ruby 2.6.6, the issue is still there.

**Comment by hupeng2006** [comment]
nobody give a shit about it .  So is Tk dead for ruby ? Or, is ruby dying?

**Comment by jeremyevans** [comment]
It's not that nobody cares, it's that nobody has had time to look into this yet.  ruby-tk just had a recent release, it is certainly not dead.

FWIW, this appears to be a low priority issue, because you can just include tk last and that should be an adequate work around.  Is there a reason you can't do that until someone has had time to find the cause of this issue?

**Comment by hsbt** [comment]
@hupeng2006 CAUTION: Your comment is offensive and disrespectful. In the next time, Iwill ban you from ruby org.

**Comment by amatsuda** [comment]
@hupeng2006 I was actually interested on this issue, and so tested your script on my box, but your issue never reproduced neither on Ruby 2.6, 2.7, and 3.0-dev here.
  We need more information about your environment, e.g. operating system, how you built tcltklib and this gem, which Ruby version manager do you use (or not use), number of gems installed in your environment, how does the performance change if you run that script with Bundler, etc.

**Comment by hupeng2006** [comment]
> It's not that nobody cares, it's that nobody has had time to look into this yet. ruby-tk just had a recent release, it is certainly not dead.
> 
> FWIW, this appears to be a low priority issue, because you can just include tk last and that should be an adequate work around. Is there a reason you can't do that until someone has had time to find the cause of this issue?

> @hupeng2006 CAUTION: Your comment is offensive and disrespectful. In the next time, I will ban you from ruby org.

Guys, Sorry for my comments. I appologize and take it back.  I love Ruby and I use it heavily both at work and privately. It is my programming lang. of choice. I certainly do not want it to disappear. I am just getting a bit frustrated recently with the loading speed of ruby-tk. I will provide detail and hope it will get fixed in the future.

**Comment by hupeng2006** [comment]
> It's not that nobody cares, it's that nobody has had time to look into this yet. ruby-tk just had a recent release, it is certainly not dead.
> 
> FWIW, this appears to be a low priority issue, because you can just include tk last and that should be an adequate work around. Is there a reason you can't do that until someone has had time to find the cause of this issue?

Yes ,you are right. I put tk at last as a workaround.  I should be more patient. ^-^

**Comment by hupeng2006** [comment]
> @hupeng2006 I was actually interested on this issue, and so tested your script on my box, but your issue never reproduced neither on Ruby 2.6, 2.7, or 3.0-dev here.
> We need more information about your environment, e.g. operating system, how you built tcltklib and this gem, which Ruby version manager do you use (or not use), number of gems installed in your environment, how does the performance change if you run that script with Bundler, etc. in order to understand what's happening.

thanks for investigating the issue.  Sorry that I did not provide more info.  I use a windows 10 pc.  I installed ruby-dev using ruby windows installer and  tk is installed using "gem install tk".  In the process, tcltklik lib is compiled with development env and created.  I do not use ruby version manager (have to uninstall old ruby version and install new one).  Below is output of "gem list --local" on my pc.  I am familiar with Bundler. Is not it a tool for package ruby app? 

 `C:\Users\penghu>gem list --local

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
cmath (default: 1.0.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
logger (default: 1.3.0)
matrix (default: 0.1.0)
mini_portile2 (2.4.0)
minitest (5.11.3)
mutex_m (default: 0.1.0)
net-ssh (6.1.0)
net-telnet (0.2.0)
nokogiri (1.10.10 x64-mingw32)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.3)
rdoc (default: 6.1.2)
rexml (default: 3.1.9)
rss (default: 0.2.7)
ruby-prof (1.4.2 x64-mingw32)
rubyXL (3.4.16)
rubyzip (2.3.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
svg-graph (2.2.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thwait (default: 0.1.0)
tk (0.3.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)`

**Comment by jeremyevans** [comment]
Looking at the difference between loading tk before sequel:

```
 23.29      8.121     2.412     0.000     5.709       48  *Kernel#require_relative        
 20.07      2.079     2.079     0.000     0.000      576   <Class::File>#file?            
 12.53      1.297     1.297     0.000     0.000      428   <Class::File>#join             
  6.97      7.552     0.722     0.000     6.830      196  *Array#each                     
  6.62      0.685     0.685     0.000     0.000      171   <Module::Gem>#suffixes         /usr/local/lib/ruby/2.7/rubygems.rb:1030
  6.26      8.299     0.648     0.000     7.651       20  *Kernel#gem_original_require    
  5.58      0.577     0.577     0.000     0.000      255   Gem::StubSpecification#data    /usr/local/lib/ruby/2.7/rubygems/stub_specification.rb:111
  4.04      0.418     0.418     0.000     0.000      117   String#initialize_copy         
  2.72      0.281     0.281     0.000     0.000      113   <Class::File>#symlink?         
  2.32      0.241     0.241     0.000     0.000      345   <Class::File>#expand_path      
```

vs. after:

```
 62.43      0.183     0.119     0.000     0.064       48  *Kernel#require_relative        
 13.76      0.183     0.026     0.000     0.157       20  *Kernel#gem_original_require    
  3.84      0.007     0.007     0.000     0.000      183   Module#class_eval              
  2.16      0.010     0.004     0.000     0.006        2   Integer#times                  
  2.09      0.004     0.004     0.000     0.000       31   Regexp#initialize              
  2.00      0.004     0.004     0.000     0.000      462   <Class::File>#file?            
  1.78      0.003     0.003     0.000     0.000     1280   String#%                       
  1.19      0.068     0.002     0.000     0.065      158  *Array#each                     
  1.03      0.002     0.002     0.000     0.000      231   <Class::File>#expand_path      
  1.01      0.002     0.002     0.000     0.000     2560   String#-@                    
```

It doesn't appear to be a single thing slowing things down, it seems everything is slower, sometimes by a factor of 100.

This doesn't appear to be related to rubygems at all.  Everything is slower after loading tk, even without rubygems:

```
$ time ruby --disable-gems -I tmp/tk/lib -rtk -e "i = 0; 1000.times{File.file?('.')}"                             
    0m04.96s real     0m00.09s user     0m00.03s system
$ time ruby --disable-gems -I tmp/tk/lib -e "i = 0; 1000.times{File.file?('.')}"      
    0m00.02s real     0m00.00s user     0m00.03s system
```

After some debugging, this is due to the Tk interpreter thread, as killing it restores the performance:

```
$ time ruby --disable-gems -I tmp/tk/lib -rtk -e "TkCore::INTERP_THREAD.kill; i = 0; 1000.times{File.file?('.')}" 
    0m00.10s real     0m00.07s user     0m00.04s system
```

There is actually a one line fix, at least for this example, but I assume it must cause other problems:

```diff
diff --git a/lib/tk.rb b/lib/tk.rb
index afa359b..b07459d 100644
--- a/lib/tk.rb
+++ b/lib/tk.rb
@@ -1210,7 +1210,7 @@ module TkCore
 =end
           end
         else
-          RUN_EVENTLOOP_ON_MAIN_THREAD = false
+          RUN_EVENTLOOP_ON_MAIN_THREAD = true
         end
 
       else # Ruby 1.8.x
```

**Comment by hupeng2006** [comment]
> ```diff
> diff --git a/lib/tk.rb b/lib/tk.rb
> index afa359b..b07459d 100644
> --- a/lib/tk.rb
> +++ b/lib/tk.rb
> @@ -1210,7 +1210,7 @@ module TkCore
>  =end
>            end
>          else
> -          RUN_EVENTLOOP_ON_MAIN_THREAD = false
> +          RUN_EVENTLOOP_ON_MAIN_THREAD = true
>          end
>  
>        else # Ruby 1.8.x
> ```

hi Jeremy, thanks for investigating the issue.  Applying this one line fix,  now my app starts up much faster. ^~^ 
I will check if this would affect my app in other ways. 
So, regarding setting "RUN_EVENTLOOP_ON_MAIN_THREAD = true",  I have a quetion.  If the tk interpreter is running in the main thread (which is the case in my app), then it would be fine.  Is my understanding correct?

**Comment by jeremyevans** [comment]
Unfortunately, I'm not sure.  I don't know exactly what `RUN_EVENTLOOP_ON_MAIN_THREAD` does and why it would be false by default.   I assume it is because if you are running any Ruby code in your application, the UI will not update when the Ruby code is being run, unless you are manually running that code in a separate thread.  However, that is only a guess based on the name of the constant.

**Comment by hupeng2006** [comment]
> Unfortunately, I'm not sure. I don't know exactly what `RUN_EVENTLOOP_ON_MAIN_THREAD` does and why it would be false by default. I assume it is because if you are running any Ruby code in your application, the UI will not update when the Ruby code is being run, unless you are manually running that code in a separate thread. However, that is only a guess based on the name of the constant.

Jeremy, thanks for your explanation (guess).  In the case of my app,  the main thread is actually doing the job of creating/arranging/updating GUI widgets.  So settting `RUN_EVENTLOOP_ON_MAIN_THREAD` to "true" does seem right...  I will test my app and post issue here if there is any.

**Comment by jeremyevans** [comment]
I tested this with my apps that use tk and it makes them startup way faster.  Looking in the repository history, I can't determine why `RUN_EVENTLOOP_ON_MAIN_THREAD` was set to false.  It would be great to get feedback from more people using ruby/tk to see whether this causes problems in their applications.  If no problems are caused, it seems like we should definitely switch, considering how significant the performance increase is.
