### ISSUE TITLE
Small warnings issued by the tk gem - could these be removed by someone with commit access?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby/tk#29]
Hello there.

Requiring the tk-gem leads to lots of warning messages.

I'll go through them:

https://github.com/ruby/tk/blob/master/lib/tk.rb#L821

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:821: warning: assigned but unused variable - id

The line:

    id = "c" + TkCore::INTERP._ip_id_ + TkComm::Tk_IDs[0]

I would probably simply add an explicit return, or just "id" as the last value there:

    return id

https://github.com/ruby/tk/blob/master/lib/tk.rb#L3490

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:3491: warning: assigned but unused variable - e

The line:

    rescue => e

I would either remove the "=> e" part, or if you want to keep it:

    rescue => _e
    rescue => _error
    rescue => _exception

Something like that.

Hmm many more such small warnings, at lines
3551, 3807, 3951, 4054.

Also a method is redefined here:

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:1369: warning: method redefined; discarding old to_s

Not sure why.

At line 887:

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:887: warning: instance variable @cmdtbl not initialized

This one is not initialized. Perhaps a reset() method or something like this
could be used to initialite all these variables.

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:2533: warning: instance variable encoding_table not initialized

Then another small warning in winfo.rb:

    /root/.gem/gems/tk-0.3.0/lib/tk/winfo.rb:242: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument

And some warnings like:

    /root/.gem/gems/tk-0.3.0/lib/tk.rb:2855: warning: instance variable @encoding not initialized

Perhaps if someone with commit rights could go through these? These are mostly trivial
to fix; not sure if it is possible to do so via the web-interface.

**Comment by jeremyevans** [comment]
Did you try #24 ?

**Comment by jeremyevans** [comment]
I merged #24, so if you are still seeing warnings with the master branch, please post which ones.
