### ISSUE TITLE
warning: undefining the allocator of T_DATA class TkUtil::CallbackSubst::Info

### ISSUE THREAD

**Issue by lain0** [ruby/tk#52]
With ruby 3.2.2 i still got warning 
```ruby
3.2.2 :001 > require 'tk'
/Users/serj/.rvm/gems/ruby-3.2.2/gems/tk-0.4.0/lib/tkutil.bundle: warning: undefining the allocator of T_DATA class TkUtil::CallbackSubst::Info
```

look like this doesn't work
https://github.com/ruby/tk/commit/bf02b2aaa1e4d7688b84ea771a56d9d53e63015c

**Comment by jeremyevans** [comment]
That commit was made on January 1, 2023.  It looks like you are using tk 0.4.0 (latest release, not the master branch), which was released March 21, 2021.  The commit does work, you just aren't using it.  I guess what you actually want is a release. :)  I'll see I can release the current master branch later this week.

**Comment by jeremyevans** [comment]
tk 0.5.0 gem has been released.
