### ISSUE TITLE
extconf.rb ignores config_list.in

### ISSUE THREAD

**Issue by adbennet** [ruby/tk#54]
Hi, I installed ruby, ruby-dev, tk-dev from the MX Package Installer. If you want the versions I can give them, but as far as I can see it's not important for this issue. **gem install tk** could not find the libraries, etc. I followed the **README.tcltklib** and added the build variables to **config_list.in**, but this made no difference whatsoever, same errors as before. 

A closer look at **extconf.rb** showed that it is not handling the **mkmf** methods correctly, so I patched **extconf.rb**, and per the readme I was able to do **ruby extconf.rb** followed by **make** and **make install**. But this did not give me gem. (By the way, even when I gave the correct tclConfig.sh and tkConfig.sh, it still ignored them even though the include and lib paths are in there. But I didn't investigate any further because I could use the include and lib build variables.)

Another **gem install tk** of course wiped out my ext/tk changes and produced the same errors as before. However, I finally succeeded by appending all my build variables to the command line. Again, I can show the variables, but the point is they are the same as what I put in **config_list.in**.

My patch to **extconf.rb** attached. I just started learning Ruby so it's quite possible my patch is not perfect, but I think is a step in the right direction.
[extconf-rb.patch.txt](https://github.com/ruby/tk/files/13714226/extconf-rb.patch.txt)

**Comment by jeremyevans** [comment]
Considering that almost all installs are using `gem install tk`, I don't know if expanding the support for `config_list.in` make sense.  Maybe we should update the documentation so that instead of mentioning `config_list.in`, it instructs how to set the correct arguments when calling `gem install tk`.

**Comment by adbennet** [comment]
Okay sure, better documentation is also better. I installed rubytk gem again on a different machine using various combinations of arguments. Based on my experiments, tclConfig.sh and tkConfig.sh are useless. Sourcing them didn't add any variables to the environment (at least I couldn't figure it out), and when passed as arguments extconf.rb again did not succeed in getting the needed include(s) and lib(s). I think the absolute minimum arguments to provide would be (adjusted for the correct paths):
* --with-tcl-include='/usr/include/tcl8.6' 
* --with-tk-include='/usr/include/tcl8.6' 
* --with-tcl-lib='/usr/lib/x86_64-linux-gnu' 
* --with-tk-lib='/usr/lib/x86_64-linux-gnu' 

What I actually did was this one:
    $ sudo gem install tk -- --without-ActiveTcl --without-tcltk-framework --without-tclConfig-file --without-tkConfig-file --with-tcl-include='/usr/include/tcl8.6' --with-tk-include='/usr/include/tcl8.6' --with-tcl-lib='/usr/lib/x86_64-linux-gnu' --with-tk-lib='/usr/lib/x86_64-linux-gnu' --with-X11 --with-X11-include='/usr/include/X11' --with-X11-lib='/usr/lib/x86_64-linux-gnu' --enable-pthread --enable-tcl-thread --enable-space-on-tk-libpath
    Building native extensions with: '--without-ActiveTcl --without-tcltk-framework --without-tclConfig-file --without-tkConfig-file --with-tcl-include=/usr/include/tcl8.6 --with-tk-include=/usr/include/tcl8.6 --with-tcl-lib=/usr/lib/x86_64-linux-gnu --with-tk-lib=/usr/lib/x86_64-linux-gnu --with-X11 --with-X11-include=/usr/include/X11 --with-X11-lib=/usr/lib/x86_64-linux-gnu --enable-pthread --enable-tcl-thread --enable-space-on-tk-libpath'
    This could take a while...
    Successfully installed tk-0.5.0
    Parsing documentation for tk-0.5.0
    Installing ri documentation for tk-0.5.0
    Done installing documentation for tk after 4 seconds
    1 gem installed
    $ 

MX-23.1_ahs_x64 Libretto October 15  2023 base: Debian GNU/Linux 12 (bookworm)
from the repository: ruby (1:3.1) ruby-dev (1:3.1) tcl-dev (8.6.13) tk-dev (8.6.13) +Recommended 

As far as config_list.in, I could be wrong (although I think I'm right): I'm pretty sure the code in extconf.rb shows a misunderstanding of how to handle mkmf. Even if nobody cares about config_list.in, the rest of extconf.rb might need checking because misunderstandings like that don't stay in one place. I tried to look at how extconf.rb handles tclConfig.sh and tkConfig.sh, but it was pretty puzzling, too much time looking stuff up in my ruby reference, so I let it go.

**Comment by jeremyevans** [comment]
The options you gave are the ones I use.

You are probably correct about extconf.rb.  I'm definitely not a mkmf expert, and I'm hesitant to make changes that I wouldn't fully understand the consequences of.  However, updating the documentation (maybe the README) to demonstrate the use of arguments to `gem install` seems like a good idea
