### ISSUE TITLE
tk on windows with ActiveTcl and ruby 3.2 crashing

### ISSUE THREAD

**Issue by andrewroth** [ruby/tk#58]
Hi, I've followed the guide at https://tkdocs.com/tutorial/install.html#install-win-ruby.

I've installed the latest ruby at [Ruby+Devkit 3.2.3-1 (x64)] https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.3-1/rubyinstaller-devkit-3.2.3-1-x64.exe) and the latest ActiveTcl install ActiveTcl-8.6.13.0000-MSWin32-x64-559160e0.msii.

I've set the env vars, copied the dll's to ruby's bin as said in the guide.

The crash seems to have no further information other than it's just failed. Any ideas? Thanks.

```
H:\Development\tk_ruby_test>echo %TCL_LIBRARY%
C:\ActiveTcl\lib\tcl8.6

H:\Development\tk_ruby_test>echo %TK_LIBRARY%
C:\ActiveTcl\lib\tk8.6

H:\Development\tk_ruby_test>irb
irb(main):001:0> require "tk"
#<Thread:0x000002976c3a1938 C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1178 run> terminated with exception (report_on_exception is true):
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:32:in `initialize': tcltklib: fail to Tk_Init().  (RuntimeError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:32:in `initialize'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1181:in `new'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1181:in `block in <module:TkCore>'
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:32:in `initialize': tcltklib: fail to Tk_Init().  (RuntimeError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:32:in `initialize'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1181:in `new'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/tk-0.5.0/lib/tk.rb:1181:in `block in <module:TkCore>'
<internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- tk (LoadError)
        from <internal:C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from (irb):1:in `<main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from C:/Ruby32-x64/bin/irb:33:in `load'
        from C:/Ruby32-x64/bin/irb:33:in `<main>'
irb(main):002:0>
```

**Comment by andrewroth** [comment]
I got further with the latest 2.7 windows release. https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.7.8-1/rubyinstaller-devkit-2.7.8-1-x64.exe. So somewhere between that version and the latest it broke.

Also python gave more info:

```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter as tk
>>> window = tk.Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\tkinter\__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    {C:\ActiveTcl\lib\tk8.6} C:/ActiveTcl/lib/tcl8.6/tk8.6 C:/ActiveTcl/lib/tk8.6 C:/lib/tk8.6 C:/lib/tk8.6 C:/lib/tk8.6 C:/library

C:/ActiveTcl/lib/tk8.6/tk.tcl: version conflict for package "Tk": have 8.6.12, need exactly 8.6.13
version conflict for package "Tk": have 8.6.12, need exactly 8.6.13
    while executing
"package require -exact Tk  8.6.13"
    (file "C:/ActiveTcl/lib/tk8.6/tk.tcl" line 14)
    invoked from within
"source C:/ActiveTcl/lib/tk8.6/tk.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $file]"


This probably means that tk wasn't installed properly.

>>> window = tk.Tk()
>>>
```

So then I modified C:\ActiveTcl\lib\tcl8.6\init.tcl and C:\ActiveTcl\lib\tk8.6\tk.tcl, near the start of those files is `package require -exact Tcl 8.6.13` and `package require -exact Tk  8.6.13`, respectively. So I modified those to be `package require -exact Tcl 8.6.12` and `package require -exact Tk  8.6.12`, and it worked!

So is this an issue with ActiveCtl's install? Did they include maybe 8.6.12 in the dll's or elsewhere in their own package, but then require 8.6.13 in the lib files?

**Comment by jeremyevans** [comment]
Not sure what the problem is, but I suspect you are correct this is an issue with ActiveTcl and not ruby-tk.  Unfortunately, I don't have any experience using ruby-tk on Windows.

**Comment by AndyObtiva** [comment]
@andrewroth I just wanted to note that the [Glimmer DSL for Tk](https://github.com/AndyObtiva/glimmer-dsl-tk) project, which runs on top of Ruby Tk and ActiveTcl, includes detailed Windows setup instructions for how to get ActiveTcl and Ruby Tk installed and working:  https://github.com/AndyObtiva/glimmer-dsl-tk?tab=readme-ov-file#pre-requisites

That might help.
